name: Terraform CI

on:
  pull_request:
    paths: ["**/*.tf", "**/*.tfvars"]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Day-06-Terraform-CICD-and-Best-Practices

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Format
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan